### ISSUE TITLE
[SoM] Reflector returning exit code zero when error due to required module not being -I/-L'ed 

### ISSUE THREAD

**Issue by chamons** [xamarin/binding-tools-for-swift#116]
While looking at [this issue](https://github.com/xamarin/maccore/issues/936) I came across a bug in the reflector.

If we have two modules, one referencing another, and don't pass the correct flags to the referred to lib in reflection, we get an error but continue on since the exit code is wrong. 

`
/Users/donblas/Programming/maccore/tools/tom-swifty/SwiftToolchain-v2-10030bbcb0fb2e42a26d43cea70662fb6a019b9a/build/Ninja-DebugAssert/swift-macosx-x86_64/bin/swift -xamreflect -target x86_64-apple-macosx10.9 -sdk /Applications/Xcode92.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -I ~/tmp/swift_reflect/consumer/ -L ~/tmp/swift_reflect/consumer/  -F /Users/donblas/Programming/maccore/tools/tom-swifty/swiftglue/bin/Debug/mac/FinalProduct -L /Users/donblas/Programming/maccore/tools/tom-swifty/SwiftToolchain-v2-10030bbcb0fb2e42a26d43cea70662fb6a019b9a/build/Ninja-DebugAssert/swift-macosx-x86_64/lib/swift/macosx -o liboutput_consumer.xml Consumer
`
```
<unknown>:0: error: missing required module 'Lib'
```
```
$ echo $?
0
```
- [swift_reflect.zip](https://github.com/xamarin/maccore/files/2287494/swift_reflect.zip)

**Comment by stephen-hawley** [comment]
Notes for future Steve - not seeing anything obvious:
`main` returns `run_driver`.
`run_driver` if the first arg is `-xamreflect`  returns `xamreflect_main`
`xamreflect_main` returns:
0 on success
1 on empty args
1 if args don't parse
1 if `Instance.setup` returns non-zero

notes:
- if the output file can't be opened, we should probably also return 1, otherwise we're setting up a crash.
- if no modules load, we return 0, but we do generate (empty) XML.

With regards to the last bit, the reflector was built to reflect on multiple modules in one shot. We could modify the code to detect if only one module was provided and error out if that module didn't load.

**Comment by stephen-hawley** [comment]
Fixed.
