### ISSUE TITLE
Consider aligning Xcode.app filename convention with xamarin-macios

### ISSUE THREAD

**Issue by rdavisau** [xamarin/binding-tools-for-swift#168]
I think that xamarin-macios and binding-tools-for-swift have different expectations wrt how Xcode versions are named. 

binding-tools seems to want `Xcode_V.v.vv.app`
where xamarin-macios would want something more like `XcodeVvvv.app`

If there's no technical reason for the difference, it might be nice to standardise on one filename format.

**Comment by rolfbjarne** [comment]
Eventually we're going to move xamarin-macios to the format used here (because the format used here is also used by several other teams, while xamarin-macios pretty much stands alone in its naming). The format used here is also the same format used in Azure Pipelines.

If you already have a particular version of Xcode installed using the wrong name, you can just create a symlink for the right name.
