### ISSUE TITLE
[Question] Will it support any versions of xcode?

### ISSUE THREAD

**Issue by roubachof** [xamarin/binding-tools-for-swift#184]
For now prerequisites list is pretty big and annoying for someone already using a mac as a Xamarin build machine.
If I want to use the binding tool, I basically need to create another mac vm just for it.
So is it planned to support latest versions of xcode and xamarin/mono sdk?
Or should I need to setup a new VM different from my every day mac build host?

**Comment by stephen-hawley** [comment]
Hi @roubachof ! Thanks for asking about this.
One of the issues that we have to address in Binding Tools for Swift (BTfS) is that we need to be able to look at the entire front-facing API of a swift module. We tried looking only at the final binary, but while demangling gives us most of the information we need, it's missing a number of key things like attributes. The solution we adopted was to modify the swift compiler itself, which can consume `.swiftmodule` files, from which we can generate reflection information on all the types and functions.
The problem with this is that the `.swiftmodule` is a binary serialization of the abstract syntax tree and it changes with every compiler release, so right now BTfS is keyed to a particular version of the compiler.

In the future, we fully intend to support `.swiftinterface` files which are supposed to be language and compiler version agnostic. In theory, the existing reflection extensions can consume these since our interfacing to the compiler doesn't make a lot of assumptions about what comes in. The code that calls the reflector and the code that handles command line parameters needs to know about `.swiftinterface` files and that's where most of the work would have to come into play.

I would also love to drop the compiler extension entirely and instead have a parser that can consume `.swiftinterface` files on its its own. Not only would this reduce the size of the distributable, it would also speed up the process. I think the additional maintenance cost of a parser is worth the benefit.

**Comment by roubachof** [comment]
Thanks @stephen-hawley great explanation!
I know it's an irritating question (I am an oss maintainer x), but do you have a general idea of the release date for the support of .swiftinterface?
There is no rush, this is just to help me decide if I can wait some time or just setup a new VM :)

**Comment by stephen-hawley** [comment]
I'd like to offer you a date on this, but right now our high priority task is getting protocols with associated types working. At the point when we update to working with Swift 5.current, we'll probably put in support for `.swiftinterface` files since the tasks are related.
Thanks again for asking!
